sudo: false
language: go
go:
- 1.6
install:
- go get github.com/constabulary/gb/...
script:
- make test
notifications:
  email: false
  slack:
    secure: m5u4F6qpUh358wHL2FmH0Vst6aFIOLJLCRwPMFduBxrDG6ZorztfcSCMXVYin19/h0yLS5eY1l9ldeG7je3uQpKMMEA0T1SgOLp/0VlSS6PI/yn8nxvTZV8YojJoEMfPOlrwj0jGUygxx9hie5ob/1JRMTz+ORtfvOuSR2yZH6EiDct2tJJm2FduA/q4pmuNowW5pSZ7YdrlV5f14+Uq0yWZ4Ks1SZWAXNqvPWF+uMNiI+5/xouwadF5Z44vHqKnGDiUbW47XXDN5VkwMWBApMbXqeGDV44dErXamHXYy/yGaitUBehpc29KSFkdEvH55vocUWnydILkZhloG41l1M73FlJDVtl91kLo94ARTj9rwV18NR2j/w0Y4eMORFF+Nq4T6ELWbGTKm2Lutha+wdmcfNg0O772JcN/X743ISCJ1dDMYaE3dudltip24cluzaY8zRtTt7Qj+33vENCmwX9B2FXsYUpAN9d9b46MWjLFo9Q1dkzZBPbmqx3XilSZhSNZGdoWK+BYQYFx2dRloF/FmTOUnH8aHP3d8EUclC9a8gEsHrFAafsMZBXCiypGI8VYExyoRMXA4P53qNCnVdxnjel113ACV22zJGJtH1m2qel9ZF5B6RP0hZOEE82EQIAFQNv/b1+dcqawBO7rzRl6VxT/Z0+kAN8TMl/O4no=
