version: 0.4
outputdir: ./bin
scripts:
  fmt: goimports -w src
projects:
  - name: content
    type: go
    root: src/cmd/otsimo-content
    imageName: gcr.io/otsimocloud/content
    dockerfile: ./Dockerfile
    run: ./content --debug --git-path ./project --host http://127.0.0.1:18871 --git-branch deneme
    golang:
      package: cmd/otsimo-content
      cgoEnabled: false
      ldflags: "-w -X main.Version=${BUILD_VERSION}"
      builder: gb
    develop:
      keepdata: false
      ports:
        - "18859:18859"
      command:
        - /opt/otsimo/content
        - --debug
        - --git-path
        - /opt/wiki
        - --host
        - http://192.168.64.8:18859
