#!/bin/bash

source ./script/common

if [ "$1" = "cross" ]; then

    echo "Cross build for linux and osx"
    env GOOS=linux GOARCH=amd64 gb build -ldflags "-X main.Version=$BUILD_VERSION"
    env GOOS=darwin GOARCH=amd64 gb build -ldflags "-X main.Version=$BUILD_VERSION"

elif [ "$1" = "docker" ]; then

    echo "Cross build for linux amd64"
    env GOOS=linux GOARCH=amd64 gb build -ldflags "-X main.Version=$BUILD_VERSION"

else

    echo "Build for" $(go env GOOS)
    env GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) gb build -ldflags "-X main.Version=$BUILD_VERSION"

fi